### ISSUE TITLE
Make error and hanging_indent_bib source file fix

### ISSUE THREAD

**Issue by ealvar3z** [shushcat/mla_paper_template#1]
Good evening Sir,

I submitted a PR to fix the following issues:

- outdated `pandoc` commands in the `Makefile`
- corrected syntax erros in the `hanging_indent_bib.latex` source file.

Please see attached asciicasts:
---
1. the actual make error: [![asciicast](https://asciinema.org/a/408644.svg)](https://asciinema.org/a/408644)
2. a rudimentary test:  [![asciicast](https://asciinema.org/a/408647.svg)](https://asciinema.org/a/408647)

Thank you for making and sharing the project.

**Comment by shushcat** [comment]
Hi there---Thanks for drawing my attention to this project, and for the suggestions.  I haven't accepted your pull request because the "-s" flag does not replicate the deprecated "-S" flag, and there were several other changes that needed to be made to get the bibliography style working with Pandoc's new, internal implementation of citeproc.  I followed your lead on appending "%" to the lines in the renew command for the "Works Cited" section, but found that [the Koma Script article class](https://www.ctan.org/pkg/scrartcl) has internal commands for changing section behavior, so, seeing no reason not to, followed the blessed path.  In any case, the project should compile again now.
